# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0005_auto_20161208_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='base_url',
            field=models.URLField(default='http://127.0.0.1:8000/shorturl/'),
        ),
    ]
