# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesearch',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='imagesearch',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='imagesearch',
            name='page_url',
        ),
        migrations.AddField(
            model_name='imagesearch',
            name='term',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
    ]
